#!/usr/bin/env python3
"""Generate the plugin's commands/ from the adapters in .claude/commands/.

Familiar installs two ways, and each needs the same commands written slightly
differently.

`scripts/setup.sh` copies an adapter into an agent's own command folder and
substitutes the real paths on the way, because at that moment it knows where
this clone sits and where the writer keeps their knowledge. A plugin has no
such moment: its files are shipped as they are and read wherever the plugin
was unpacked. So the paths cannot be baked. They become `${CLAUDE_PLUGIN_ROOT}`,
which the host expands, and a knowledge folder the command resolves for itself
by running paths.py.

`.claude/commands/` stays the source of truth. This script writes commands/,
the result is committed so the plugin needs no build step, and a test
regenerates it to catch the two drifting apart.

    python3 scripts/build-plugin.py           write commands/
    python3 scripts/build-plugin.py --check   exit 1 if it is out of date
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADAPTERS = ROOT / ".claude" / "commands"
OUT = ROOT / "commands"

# The plugin root is the Familiar folder: the marketplace entry points at the
# repository itself, so prompts/, scripts/ and AGENTS.md all sit beneath it.
HOME = "${CLAUDE_PLUGIN_ROOT}"

# Knowledge is the writer's, not the plugin's, and no two installs agree on
# where it lives. The adapters name it as a path; here it becomes the one
# instruction that finds it. Backticked first, so the sentence it sits in
# still reads as a sentence.
KNOWLEDGE_QUOTED = (
    "the folder that `python3 ${CLAUDE_PLUGIN_ROOT}/scripts/paths.py "
    "--knowledge-only` prints"
)
KNOWLEDGE_BARE = KNOWLEDGE_QUOTED

BANNER = (
    "<!-- Generated by scripts/build-plugin.py from .claude/commands/. "
    "Edit the adapter there, not this file. -->\n"
)


def render(text):
    """One adapter, rewritten for a plugin install."""
    # The quoted form first: `{{FAMILIAR_KNOWLEDGE}}` carries its own backticks
    # in the adapters, and leaving them would nest a command inside a path.
    text = text.replace("`{{FAMILIAR_KNOWLEDGE}}`", KNOWLEDGE_QUOTED)
    text = text.replace("{{FAMILIAR_KNOWLEDGE}}", KNOWLEDGE_BARE)
    text = text.replace("{{FAMILIAR_HOME}}", HOME)
    return text


def place_banner(text):
    """Put the banner under the frontmatter, so the frontmatter stays first."""
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            cut = end + len("\n---\n")
            return text[:cut] + BANNER + text[cut:]
    return BANNER + text


def build():
    """Every adapter, rendered. Returns {filename: contents}."""
    out = {}
    for src in sorted(ADAPTERS.glob("*.md")):
        out[src.name] = place_banner(render(src.read_text()))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report drift instead of writing")
    args = ap.parse_args()

    if not ADAPTERS.is_dir():
        print("No .claude/commands/ to build from.", file=sys.stderr)
        return 1

    wanted = build()

    if args.check:
        stale = []
        for name, body in wanted.items():
            target = OUT / name
            if not target.is_file() or target.read_text() != body:
                stale.append(name)
        # A command taken out of .claude/commands/ has to go from here too. A
        # left-behind command still shows in the agent's list and calls a
        # prompt that is no longer there.
        if OUT.is_dir():
            stale += [p.name for p in OUT.glob("*.md") if p.name not in wanted]
        if stale:
            print("commands/ is out of date: " + ", ".join(sorted(set(stale))))
            print("Run scripts/build-plugin.py and commit the result.")
            return 1
        print("commands/ is up to date.")
        return 0

    OUT.mkdir(exist_ok=True)
    for name, body in wanted.items():
        (OUT / name).write_text(body)
    removed = []
    for p in OUT.glob("*.md"):
        if p.name not in wanted:
            p.unlink()
            removed.append(p.name)

    print(f"Wrote {len(wanted)} command{'s' if len(wanted) != 1 else ''} to commands/")
    for name in sorted(wanted):
        print(f"  {name}")
    if removed:
        print("  took out: " + ", ".join(sorted(removed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
