#!/usr/bin/env python3
"""Check a draft against knowledge/never-publish.md.

Familiar reports and never rewrites. This is the exception, and it is narrow on
purpose: it does not refuse to write anything, it refuses to send. Drafting is
private and reversible. Publishing is not.

Two severities, because a check that cries wolf gets switched off:

  block  names and money. Exit 1. A match is almost certainly real.
  warn   numbers and phrases. Exit 0. A match needs a person to look.

Usage:
  never-publish.py <file>        check a file
  never-publish.py -             check stdin
  never-publish.py --list        show what is loaded, without the strings

Exit 0 clean or warnings only, 1 blocked, 2 could not run.
"""
import datetime
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import paths

WORDS = re.compile(r"[A-Za-z][A-Za-z\s.'&-]*$")


STALE_AFTER_DAYS = 14


def load():
    """Return (state, block, warn). state is on, off, unresolved or stale.

    "off" and "cannot check" used to be the same answer, and publish.md
    documented that as "nothing happens and nothing is said". For a writer who
    never made a list that is right, and Familiar is a public tool. For a
    writer who has one, a check that quietly stops running is the worst
    possible outcome, because the gate reports clean.

    unresolved: a house is configured and resolution still fell back to the
                shipped templates. That is a misconfiguration, not a choice.
    stale:      the list is generated by another tool and has not been
                refreshed. What it does not contain is unknown.
    """
    house, whose = paths.knowledge_dir()
    if whose != "yours":
        # No config at all is a new install with nothing to check. A config
        # that resolved to templates anyway is a misconfiguration.
        return ("unresolved" if paths._config_file() else "off"), [], []
    f = house / "never-publish.md"
    if not f.is_file():
        return "off", [], []
    text = f.read_text()

    gen = re.search(r"^-\s*Generated:\s*(\d{4}-\d{2}-\d{2})", text, re.M)
    if gen:
        age = (datetime.date.today() - datetime.date.fromisoformat(gen.group(1))).days
        if age > STALE_AFTER_DAYS:
            return "stale", [], []

    setting = re.search(r"^-\s*Never publish:\s*(.+)$", text, re.M)
    if setting:
        v = setting.group(1).strip().lower()
        if v.startswith("off"):
            return "off", [], []
        if v.startswith("["):          # still the template
            return "off", [], []

    def block_after(heading):
        m = re.search(rf"^## {heading}\b(.*?)(?=^## |\Z)", text, re.S | re.M)
        if not m:
            return []
        out = []
        for fence in re.findall(r"```(.*?)```", m.group(1), re.S):
            for line in fence.splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                line = re.split(r"\s\s+#", line, maxsplit=1)[0].strip()
                if not line:
                    continue
                if line.startswith("[") and line.endswith("]"):
                    continue           # untouched template placeholder
                out.append(line)
        return out

    b, w = block_after("Block"), block_after("Warn")
    return ("on" if (b or w) else "off"), b, w


def present(term, text):
    """Whole words for names, substring for money and numbers.

    Without this a three-letter client name fires inside ordinary words, the
    check becomes noise, and the writer turns it off.

    A boundary is only asked for at an end that is a word character. `\\b` after
    the full stop in "Acme Inc." wants a letter next and a sentence never
    provides one, so the entry would sit on the list matching nothing, which is
    the one failure this check cannot have.
    """
    if WORDS.match(term):
        left = r"\b" if re.match(r"\w", term) else ""
        right = r"\b" if re.search(r"\w$", term) else ""
        return re.search(left + re.escape(term) + right, text, re.I) is not None
    return term.lower() in text.lower()


def main():
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)

    state, block, warn = load()

    if args[0] == "--list":
        house, whose = paths.knowledge_dir()
        print(f"house         : {house}  ({whose})")
        print(f"never publish : {state}")
        print(f"block         : {len(block)}")
        print(f"warn          : {len(warn)}")
        return 0 if state in ("on", "off") else 2

    if state == "unresolved":
        print("never-publish: cannot check. A house is configured but resolution "
              "fell back to the shipped templates,", file=sys.stderr)
        print("               so the list could not be read. Run: "
              "python3 scripts/paths.py", file=sys.stderr)
        return 2
    if state == "stale":
        print(f"never-publish: cannot check. The list has not been refreshed for "
              f"more than {STALE_AFTER_DAYS} days,", file=sys.stderr)
        print("               so what it does not contain is unknown. Regenerate "
              "it, then publish.", file=sys.stderr)
        return 2
    if state == "off":
        return 0                        # off is a supported way to work

    src = args[0]
    try:
        text = sys.stdin.read() if src == "-" else Path(src).read_text()
    except OSError as e:
        print(f"never-publish: cannot read {src}: {e}", file=sys.stderr)
        return 2

    hits_b = [t for t in block if present(t, text)]
    hits_w = [t for t in warn if present(t, text)]

    if hits_b:
        print("BLOCKED. This text contains something on your never-publish list.")
        for t in hits_b:
            print(f"  {t}")
        print("\nRemove it, or publish with the check off if the list is wrong.")
    if hits_w:
        print("\nWorth a look before this goes out:")
        for t in hits_w:
            print(f"  {t}")
    if not hits_b and not hits_w:
        print(f"never-publish: clean ({len(block) + len(warn)} on the list)")
    return 1 if hits_b else 0


if __name__ == "__main__":
    sys.exit(main())
